### PR TITLE
 Fix HTTP verbs in path routing to match behaviour

### PR DESCRIPTION
**Pull request by aidy**

### CODE REVIEW

**Comment by ogiewon** [comment]
Would this PR break all existing applications that use Assistant-Relay?  It appears you’re asking to change the server from expecting Post requests the Get requests.  Is that correct?

**Comment by aidy** [comment]
That's right - yes.

Basically, this should jump one way or the other. Either switch to GET requests, the way that the code currently stands to receive parameters, or take the parameters from the POST body (probably as a json payload).

Either way, that's a breaking interface change.

**Comment by ogiewon** [comment]
I don’t think breaking the current interface is a good idea as it would screw up far too many existing installations. 

It works as-is.

**Comment by aidy** [comment]
Actually, I've had a change of heart.

You're right; this is a interface-breaking change. As such, we should do the *correct* thing, rather than merely the convenient thing.

The correct behaviour is that this should be a POST request (as it "creates" a new action, and is not cache-able), and a correctly formed POST request should provide the data in its body.

I'll close this PR in favour of a fresh one with that behaviour.

**Pull request closed without merging**
